apiVersion: v1
kind: Secret
metadata:
  name: billingservice-mercadopago
  namespace: default
type: Opaque
stringData:
  # Endpoint do Mercado Pago
  MERCADOPAGO_ACCESS_TOKEN: "APP_USR-SEU_TOKEN_AQUI"
  
  # Configuração de ambiente
  MERCADOPAGO_IS_SANDBOX: "true"  # Mude para "false" em produção
  
  # Email para testes (sandbox)
  MERCADOPAGO_TEST_EMAIL: "test@example.com"
  
  # Token de cartão de teste (sandbox)
  MERCADOPAGO_TEST_CARD_TOKEN: "4111111111111111"
