apiVersion: v1
kind: Secret
metadata:
  name: oficina-cardozo-db-secret
  labels:
    app: oficina-cardozo-api
stringData:
  ConnectionStrings__DefaultConnection: "Host=oficina-cardozo-db.celegsiik31m.us-east-1.rds.amazonaws.com;Port=5432;Database=oficina-cardozo-db;Username=dbadmin;Password=Z4Zc7Xa5$&tz3mPMJ6qXPe#48szc5B%;Ssl Mode=Require;Trust Server Certificate=true;"
